import type { NextPage } from "next";
import LandingPage from "./LandingPage";
import AboutPage from "./AboutPage";
import styles from "../styles/Page.module.css";
import Head from "next/head";
import { AppShell, Burger, Flex } from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import NavigationBar from "../components/NavigationBar";

const Home: NextPage = () => {
  const [opened, { toggle }] = useDisclosure();
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Athena Yim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16"/>
        <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32"/>
        <link rel="icon" type="image/x-icon" href="/favicon.ico" sizes="any" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" sizes="any" />
      </Head>
      <AppShell
        header={{ height: 60 }}
        aside={{
          width: 200,
          breakpoint: 0,
          collapsed: { desktop: !opened, mobile: !opened },
        }}
        withBorder={false}
      >
        <AppShell.Header>
          <Flex justify="flex-end" style={{padding: "2rem"}}>
            <Burger
              opened={opened}
              onClick={toggle}
              size="sm"
            />
          </Flex>
        </AppShell.Header>
        <AppShell.Aside>
          <NavigationBar />
        </AppShell.Aside>
      </AppShell>
      <LandingPage />
      <AboutPage />
    </div>
  );
};

export default Home;
