import type { NextPage } from "next";
import styles from "../styles/Page.module.css";
import Head from "next/head";
import {
  ActionIcon,
  AppShell,
  Burger,
  Container,
  Flex,
  Group,
  Stack,
} from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import { NavigationBar } from "../components/NavigationBar";
import { IconBrandGithub, IconBrandLinkedin } from "@tabler/icons-react";

const Home: NextPage = () => {
  const [opened, { toggle }] = useDisclosure();

  return (
    <div className={styles.container}>
      <Head>
        <title>Athena Yim</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          type="image/png"
          href="/favicon-16x16.png"
          sizes="16x16"
        />
        <link
          rel="icon"
          type="image/png"
          href="/favicon-32x32.png"
          sizes="32x32"
        />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" sizes="any" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" sizes="any" />
      </Head>
      <AppShell
        header={{ height: 60 }}
        aside={{
          width: 150,
          breakpoint: 0,
          collapsed: { desktop: !opened, mobile: !opened },
        }}
        withBorder={false}
      >
        <AppShell.Header>
          <Flex justify="flex-end" style={{ padding: "2rem" }}>
            <Burger opened={opened} onClick={toggle} size="sm" />
          </Flex>
        </AppShell.Header>
        <AppShell.Aside>
          <NavigationBar />
        </AppShell.Aside>
      </AppShell>
      <Stack gap="md" id="landing-page" className={styles.landingPage}>
        <h1 className={styles.title}>Athena Yim</h1>
        <Group gap="xs">
          <ActionIcon
            component="a"
            href="https://github.com/athenayim"
            target="_blank"
          >
            <IconBrandGithub style={{ width: "80%", height: "80%" }} />
          </ActionIcon>
          <ActionIcon
            component="a"
            href="https://www.linkedin.com/in/athena-yim/"
            target="_blank"
          >
            <IconBrandLinkedin style={{ width: "80%", height: "80%" }} />
          </ActionIcon>
        </Group>

        <code className={styles.code}>
          MEng Computing graduate from Imperial College London.
        </code>
      </Stack>

      <Container fluid id="about-page" className={styles.contentPage}>
        <h1 id="work-experience" className={styles.subtitle}>
          💻 Experience
        </h1>
        <ul className={styles.description}>
          <li>
            Software engineer intern @ Jump Trading Group (2023 - London, UK)
          </li>
          <li>
            Software engineer intern @ JPMorgan Chase & Co. (2022 - Glasgow, UK)
          </li>
          <li>
            Undergraduate teaching assistant @ Imperial College London
            (2021-2023 - London, UK)
          </li>
        </ul>

        <h1 id="education" className={styles.subtitle}>
          🎓 Education
        </h1>
        <ul className={styles.description}>
          <li>MEng Computing @ Imperial College London (2020-2024)</li>
        </ul>
      </Container>
    </div>
  );
};

export default Home;
