import type { NextPage } from "next";
import LandingPage from "./LandingPage";
import styles from "../styles/Home.module.css";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Athena Yim</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/325/cherry-blossom_1f338.png"
        />
      </Head>
      <LandingPage />
    </div>
  );
};

export default Home;
