import type { NextPage } from "next";
import LandingPage from "./LandingPage";
import AboutPage from "./AboutPage";
import styles from "../styles/Page.module.css";
import Head from "next/head";
import NavigationBar from "../components/NavigationBar";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Athena Yim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/x-icon" href="/images/favicon.ico" />
      </Head>
      <NavigationBar />
      <LandingPage />
      <AboutPage />
    </div>
  );
};

export default Home;
